### ISSUE TITLE
Bad hardware class id

### ISSUE THREAD

**Issue by FallingSnow** [dakatapetrov/zenbook-pro-ux501vw-sound-fix#1]
Using a UX501vw.

```bash
$ ./fix-audio.sh
cp: cannot create regular file '/sys/class/sound/hwC0D0/user_pin_configs': No such file or directory
```

I changed `hwC0D0` in `reconfig.sh` to `hwD1D0` and it worked. Also here is a list of my sound devices.

```bash
$ ls /sys/class/sound
card0  card1  controlC0  controlC1  hwC1D0  hwC1D2  pcmC0D0c  pcmC0D0p  pcmC0D1c  pcmC0D1p  pcmC1D0c  pcmC1D0p  pcmC1D10p  pcmC1D3p  pcmC1D7p  pcmC1D8p  pcmC1D9p  timer
```

Thanks for making this! :)

**Comment by dakatapetrov** [comment]
Hi, @FallingSnow ! Glad you've made it work for you :)

I'll think of a way to automatically detect the correct card config. Let me know if you have any ideas. Thanks for the feedback!

**Comment by FallingSnow** [comment]
Just reinstalled Arch Linux and your script works without any modification now.
